# Generated by Django 4.1.4 on 2022-12-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('departmentid', models.AutoField(primary_key=True, serialize=False)),
                ('departmentNames', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employeeid', models.AutoField(primary_key=True, serialize=False)),
                ('employeeName', models.CharField(max_length=100)),
                ('DepartmentName', models.CharField(max_length=100)),
                ('Dateofjoinining', models.DateField()),
                ('photo_name_emp', models.CharField(max_length=100)),
            ],
        ),
    ]
